# Generated by Django 5.1.4 on 2025-01-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSupport',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
